#Team 4J: Ezra Davis & Artian Kica

##start Makefile

prog4: header.h LinkedList.cpp RootNode.cpp Tree.cpp
	g++ -o prog4 prog4.cc 
	
test: prog4 US_Constitution.txt
	./prog4 US_Constitution.txt
	
run:
	make prog4
	make test
	
##end Makefile
